### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by rg2001** [18107/MC-Ray-Tracer#4]
Can I build this as a shader for optifine?

**Comment by 18107** [comment]
This is a completely different way of rendering the game and is not compatible with any shaders. It is mostly a test of a different type of ray tracer. Feel free to run it as a standalone, but keep in mind it is not finished and will probably not work with any mods.

**Comment by rg2001** [comment]
So this a mod? and if so what do u recommend to build it?

**Comment by 18107** [comment]
I have built the mod for Minecraft 1.11 and uploaded it to releases. Install forge, then put the mod in the mods folder. Please report back if you can't get it working. I haven't had time to test the release yet.

**Comment by rg2001** [comment]
Cheers
